version: "3"

tasks:
  github-stack:
    desc: Github Actions Stack
    dotenv: [ "{{.CLI_ARGS }}" ]
    cmds:
      - |
        # Prompt for cdk command
        echo "Please enter cdk command diff,synth,deploy etc:"
        read cdk_command
        yarn cdk:github $cdk_command

  bootstrap-account:
    desc: "Bootstrap the project"
    dotenv: [ "{{.CLI_ARGS }}" ]
    env:
      STACK_NAME: CDKToolkitIam
      STACK_QUALIFIER: iam
    cmds:
      - yarn cdk bootstrap $AWS_ACCOUNT/$AWS_REGION  --toolkit-stack-name $STACK_NAME --qualifier $STACK_QUALIFIER --cloudformation-execution-policies 'arn:aws:iam::aws:policy/AdministratorAccess'
