version: "3"

tasks:
  list-github-stack:
    desc: List github actions stack
    dotenv: [ "{{.CLI_ARGS }}" ]
    cmds:
      - |
        npx projen list:github

  synth-github-stack:
    desc: List github actions stack
    dotenv: [ "{{.CLI_ARGS }}" ]
    cmds:
      - |
        npx projen synth:github

  diff-github-stack:
    desc: Diff github actions stack
    dotenv: [ "{{.CLI_ARGS }}" ]
    cmds:
      - |
        npx projen diff:github

  deploy-github-stack:
    desc: Deploy github actions stack
    dotenv: [ "{{.CLI_ARGS }}" ]
    cmds:
      - |
        npx projen deploy:github

  bootstrap-account:
    desc: "Bootstrap the project"
    dotenv: [ "{{.CLI_ARGS }}" ]
    env:
      STACK_NAME: CDKToolkitIam
      STACK_QUALIFIER: iam
    cmds:
      - yarn cdk bootstrap $AWS_ACCOUNT/$AWS_REGION  --toolkit-stack-name $STACK_NAME --qualifier $STACK_QUALIFIER --cloudformation-execution-policies 'arn:aws:iam::aws:policy/AdministratorAccess'
